### PR TITLE
quiet elasticsearch methods

### PR DESCRIPTION
**Pull request by benghaziboy**
@mparent61 for the time being I'm just silencing all elasticsearch logs in the test environment unless they are legitimate erros

### CODE REVIEW

**Comment by benghaziboy** [comment]
errors -_-

**Comment by mparent61** [comment]
Throw a comment in there so Cameron2.0 will know what the heck his predecessor was thinking
:+1:

**Comment by benghaziboy** [comment]
Everything I stand against!!!!!!!

**Comment by benghaziboy** [comment]
:smiling_imp:

**Comment by mparent61** [comment]
Well played

**Pull request merged**
