### PR TITLE
Try to fix Travis ES versioning -- restore previous

### PR DESCRIPTION
**Pull request by mparent61**
Testing...

### CODE REVIEW

**Comment by benghaziboy** [comment]
:+1:

**Comment by MichaelButkovic** [comment]
:+1:

**Comment by mparent61** [comment]
Originally @collin was trying to get us onto the new container-based infrastructure. This runs into problems b/c the "service" command runs before the "apt" command, so it starts up the old ES 1.4.0 before getting latest package.
These tests are pretty snappy, though I can't tell if we're on old or new container infra. Going to check this in, feel free to make another attempt at container-based infra if necessary.

**Comment by mparent61** [comment]
https://github.com/travis-ci/travis-ci/issues/4542

**Pull request merged**
