### PR TITLE
exclude super features from content list

### PR DESCRIPTION
**Pull request by MichaelButkovic**
@mparent61 @benghaziboy @kand we had talked about doing this instead of using the exclude query param, so i did it

### CODE REVIEW

**Comment by benghaziboy** [comment]
👍

**Comment by kand** [comment]
So the `exclude` query param is now unused?

**Comment by MichaelButkovic** [comment]
once this is merged, yeah. we can still include it if we want, but since it's only being used for super features, i think it's fine to remove

**Comment by mparent61** [comment]
Since we already have the "exclude" query param logic, why not keep it, but have the view always append SF doc type to the exclude list? Seems like `exclude` would be handy in the future.

**Comment by MichaelButkovic** [comment]
sure, that's fair

**Comment by kand** [comment]
👍

**Comment by mparent61** [comment]
👍

**Pull request merged**
