### PR TITLE
Bulbs styles v2

### PR DESCRIPTION
**Pull request by jmelvnsn**

### CODE REVIEW

**Comment by jmelvnsn** [comment]
@collin @mparent61

**Comment by kand** [comment]
👍

**Comment by spra85** [comment]
👍  - assuming it won't break any integrating apps?

**Comment by jmelvnsn** [comment]
@spra85 AVC is the only site using bulbs-styles at the moment. I have an updated PR there: https://github.com/theonion/avclub/pull/459

**Pull request merged**
