### PR TITLE
unbreak onion marketing sc

### PR DESCRIPTION
**Pull request by MelizzaP**

### CODE REVIEW

**Comment by MelizzaP** [comment]
@MichaelButkovic @benghaziboy @mparent61 unbreaking onion special coverage. http://update-homepage-player.test.theonion.com/special/marketing

**Comment by MichaelButkovic** [comment]
👍

**Comment by mparent61** [comment]
Would you provide some context for us remote workers -- what is the problem this is fixing?  Is this a temp fix (b/c share_title is now blank..)

**Comment by MelizzaP** [comment]
the changes I made to the special coverage view, apparently only worked for the page I was testing. @benghaziboy might be able to elaborate more as to why, but apparently you can't get a video object using a videohub ref id

**Comment by mparent61** [comment]
@benghaziboy ?

**Comment by MelizzaP** [comment]
@mparent61 @benghaziboy, soooo this is broken in prod... https://trello.com/c/cCxDcYTO/505-webtech-video-issue-causing-404-on-special-coverage. This fix will at least fix the 404 until we figure out why we're not getting videos from the videohub ids

**Comment by MelizzaP** [comment]
hot test links: http://test-branch.test.theonion.com/special/entertainment
http://test-branch.test.theonion.com/special/marketing

**Pull request merged**
