### PR TITLE
Wrap twitter embeds in an iframe

### PR DESCRIPTION
**Pull request by MichaelButkovic**
@mparent61 @benghaziboy this solves our twitter embed problem https://developers.facebook.com/direct-support/question/157830444654376/

### CODE REVIEW

**Comment by collin** [comment]
It's weird that I can click on the names on the dev-support thread and I get taken to actual FB profile pages.

**Comment by mparent61** [comment]
👍

**Comment by collin** [comment]
👍

**Comment by benghaziboy** [comment]
👍

**Pull request merged**
