### PR TITLE
CMS Notification naming cleanup

### PR DESCRIPTION
**Pull request by mparent61**
To avoid collisions with new "Notification" app. 

Holding off on fully renaming to "CMS Alerts", as under time constraints and "CMS Notifications" conformance requires much less work.

**Breaking change, will require updated `bulbs-cms`**

### CODE REVIEW

**Comment by mparent61** [comment]
@MichaelButkovic @benghaziboy

**Comment by mparent61** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XomSVP3x&#x2F;110-notifications"> Notifications</a>

**Comment by mparent61** [comment]
@MichaelButkovic @benghaziboy  ready for review

**Comment by MichaelButkovic** [comment]
LGTM

**Pull request merged**
