### PR TITLE
Cut default RSS caching from 10 to 5 min

### PR DESCRIPTION
**Pull request by mparent61**
For faster RSS updates, per social squad

Will also update on 0-7-x branch

@spra85 @benghaziboy @MichaelButkovic

### CODE REVIEW

**Comment by benghaziboy** [comment]
this is supposed to impress me?

**Comment by benghaziboy** [comment]
:+1:

**Comment by spra85** [comment]
:+1: to @benghaziboy's comment.  And :+1: to the PR

**Comment by benghaziboy** [comment]
you react to my comments now, because github is social or whatever

**Pull request merged**
