### PR TITLE
Inactive special coverage honors "full_preview"

### PR DESCRIPTION
**Pull request by mparent61**
Adding check to `SpecialCoverageView.get()` was cleanest way to avoid disturbing existing access check (on first piece of content). 

Refactored common "redirect to login" logic to be shared by `BaseContentDetailView` and `SpecialCoverageView`.

### CODE REVIEW

**Comment by mparent61** [comment]
@benghaziboy @MichaelButkovic

**Comment by mparent61** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cC5SdoUQ&#x2F;545-webtech-special-coverage-previews-on-onion"> WEBTECH: Special Coverage previews on Onion</a>

**Comment by benghaziboy** [comment]
I consider you to be a very special and good person @mparent61

**Comment by MichaelButkovic** [comment]
lgtm

**Pull request merged**
