### PR TITLE
Remove old ES_URLS setting, just use ES_CONNECTIONS

### PR DESCRIPTION
**Pull request by mparent61**
- [x] Remove the need for apps to specify redundant settings
- [x] Testing: Allow ES host override via ENV (for docker-based ES) via `example.settings` module

### CODE REVIEW

**Comment by mparent61** [comment]
@MichaelButkovic @benghaziboy 

Good riddance to ES_URLS

**Comment by MichaelButkovic** [comment]
:+1:

**Comment by benghaziboy** [comment]
+

**Comment by mparent61** [comment]
Backing out so @benghaziboy can release new django-bulbs hotfix

**Pull request merged**
