### PR TITLE
Use special coverage image not content image

### PR DESCRIPTION
**Pull request by kand**
Special coverage pages should use special coverage's image, not first content's image.

### CODE REVIEW

**Comment by kand** [comment]
@spra85 @daytonn @jmelvnsn

**Comment by kand** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fk5gBY3J&#x2F;26-4-clickhole-launch"> 4. ClickHole Launch</a>

**Comment by collin** [comment]
👍

**Comment by MelizzaP** [comment]
👍

**Comment by spra85** [comment]
👍

**Comment by daytonn** [comment]
👍

**Pull request merged**
